---
title: 'Local_XAI: Boro Yield Prediction'
author: "Zia Ahmed, Unversity at Buffalo"
---

```{r}
setwd(gsub(pattern = '/scripts', replacement = '', x = getwd()))
```


#### Set working directory

```{r}
#setwd("/mnt/d/Dropbox/CIMMYT_UB/NEW_ANALYSIS/ANALYSIS/BORO/ALL_DATA")
setwd("C:\\Users\\zahmed2\\Dropbox\\CIMMYT_UB\\NEW_ANALYSIS\\ANALYSIS\\Yield\\AMAN\\XAI_Aman_Yield")
dir()
```

#### Load Pcakages

```{r message=F, warning=F}
library(plyr)
library(tidyverse)
library(dplyr)
library(classInt)
library(data.table)
library(magrittr)
library(DT)
#library(kableExtra)
require(reshape2)
#library(pROC)
library(pdp)       # for partial dependence plots (and ICE curves)
library(vip)       # for variable importance plots
library(iml)       # for general IML-related functions
library(DALEX)     # for general IML-related functions
library(lime)      # for local interpretable model-agnostic explanations
library(breakDown)
library(iBreakDown)
#library(localICE)
#library(tidyquant) #for better ggplot theme
library(purrrlyr)
```

### Load data

```{r}
mf<-read.csv("aman_union_data_all.csv", header = T)
train.mf<-read.csv("train_data.csv", header = T)
test.mf<-read.csv("test_data.csv", header = T)
```

### Create data frame-function

```{r}
FeatureData <- function(data) {
  features <- c(
                "GD",              # 1 
                "N_rate",          # 2      
                "P_rate",          # 3        
                "K_rate",          # 4        
                    
                "pH",              # 5        
                "SOC",             # 6         
                "N",               # 7         
                "P",               # 8         
                "K",               # 9         
                "S",               # 10    
                "Zn",              # 11    
               
                "DEM",             # 12
                
                "NDVI_193",      # 13
                "NDVI_205",      # 14                          
                "NDVI_225",      # 15                         
                "NDVI_241",      # 16                           
                "NDVI_257",      # 17                           
                "NDVI_273",      # 18                           
                "NDVI_289",      # 19                          
                "NDVI_305",      # 20
                "NDVI_321",      # 21
                "NDVI_337",      # 22
                "NDVI_353",      # 23  
                
                "t2m_193",      # 24
                "t2m_209",      # 25
                "t2m_225",      # 26
                "t2m_241",      # 27
                "t2m_257",      # 28
                "t2m_273",      # 29 
                "t2m_289",      # 30
                "t2m_305",      # 31                          
                "t2m_321",      # 32
                "t2m_337",      # 33
                "t2m_353",      # 34
                
                "tp_193",       # 35                           
                "tp_209",       # 36
                "tp_225",       # 37 
                "tp_241",       # 38
                "tp_257",       # 39
                "tp_273",       # 40 
                "tp_289",       # 41
                "tp_305",       # 42
                "tp_321",       # 43
                "tp_337",       # 44
                 "tp_353",      # 45 
          
                "Crop_Types",        # 46
                "LT_Class",          # 47
                "General_Soil_type", # 48
                "DRC_Class",         # 49
                "TZONE_Class",       # 50
                "Soil_texture",      # 51     
                "Water_regime",      # 52
                "Manure",            # 53      
 
                "YIELD")            # 54
                fea <- data[,features]
                fea[, 1:45] = scale(fea[, 1:45])            # scale predictors
                fea[,46:53]= dmap(fea[,46:53], as.factor)   # convert to factors 
                return(fea)
                 }
```

```{r}
df<-FeatureData(mf)
train.df<-FeatureData(train.mf)
test.df<-FeatureData(test.mf)
```

### Connect to H2o server 

```{r message=F, warning=F, results = "hide"}
library(h2o)
h2o.init(nthreads = -1,max_mem_size ="148g",enable_assertions = FALSE)
```

```{r}
h2o.no_progress() # disable progress bar for RMarkdown
h2o.removeAll()   # Optional: remove anything from previous session 
```

### Create h2o dataframe

```{r message=F, warning=F, results = "hide"}
h_df<-  as.h2o(df)
h_train<-  as.h2o(train.df)
h_test<- as.h2o(test.df)
```

### Define response and predictors

```{r}
y <- "YIELD"
x <- setdiff(names(h_train), y)
```

### Create data frame for Explianers

### All Data

```{r}
x_df <- as.data.frame(h_df) %>% dplyr::select(-YIELD)
y_df<- as.data.frame(h_df) %>% pull(YIELD)
```

### Load best model

```{r}
best_ML<- h2o.loadModel("C:\\Users\\zahmed2\\Dropbox\\CIMMYT_UB\\NEW_ANALYSIS\\ANALYSIS\\Yield\\AMAN\\XAI_Aman_Yield\\StackedEnsemble_AllModels_4_AutoML_5_20211104_162457")
```


## Create Model Explainer for Best_ML

```{r message=F, warning=F, results = "hide"}
pred_fun_best_ML <- function(object, newdata)  {
  results <- as.vector(h2o.predict(object, as.h2o(newdata)))
  return(results)
}
```

### Explainer For Training Data

```{r message=F, warning=F, results = "hide"}
explainer_df <- DALEX::explain(
  model = best_ML,
  type="regression",
  data = x_df,
  y = y_df,
  predict_function = pred_fun_best_ML,
  label = "The Best ML- Training"
)
```

## Local model interpretation

## All Data

```{r}

x <- NULL

for(i in 1:nrow(x_df)){
   x[[i]]  <-  break_down(explainer_df, 
                             new_observation = x_df[i,]
                             )
     }

```

```{r}

for (i in 1:length(x)){
  if (i==1){
    ndf <- data.frame(x[[i]]$variable_name, x[[i]]$contribution)
    names(ndf) <- c('variable_name', paste0("RowID_",i))
    ndf = ndf[order(ndf$variable_name),]
  }
  ndf1 <- data.frame(x[[i]]$variable_name, x[[i]]$contribution)
  names(ndf1) <- c('variable_name', paste0("RowID_",i))
  ndf1 = ndf1[order(ndf1$variable_name),]
  
  ndf <- cbind(ndf, ndf1[2])
  
}

```


```{r}
# delete  duplicate 

ndf$RowID_1 <- NULL
df_lc<-as.data.frame(t(ndf))
colnames(df_lc) <- df_lc[1,]
df_lc <- df_lc[-1, ] 
df_lc$Intercept <- NULL
df_lc<- df_lc[, -1] #delete column 5L

# df_lc is the final data aframe
write.csv(df_lc, "Local_contribution_aman_union.csv", row.names = TRUE)
```


